# Build LDPickupDoctor.dll and deploy it into The Long Dark's Mods folder.
#
#   powershell -ExecutionPolicy Bypass -File build.ps1              # build, check the loader, deploy
#   powershell -ExecutionPolicy Bypass -File build.ps1 -NoDeploy    # build only
#   powershell -ExecutionPolicy Bypass -File build.ps1 -Run         # deploy and start the game
#
# The .NET SDK is the user-local one at %USERPROFILE%\.dotnet. It is not on PATH on purpose: the
# machine also has a Program Files dotnet that carries runtimes and NO SDK, and "dotnet build" there
# fails with a message about downloading an SDK that is already installed elsewhere. Calling the
# full path removes the ambiguity rather than papering over it.

[CmdletBinding()]
param(
    [string]$GameDir = 'C:\Program Files (x86)\Steam\steamapps\common\TheLongDark',
    [switch]$NoDeploy,
    [switch]$Run
)
$ErrorActionPreference = 'Stop'

$root    = $PSScriptRoot
$dotnet  = Join-Path $env:USERPROFILE '.dotnet\dotnet.exe'
$project = Join-Path $root 'LDPickupDoctor.csproj'
$output  = Join-Path $root 'bin\Release\net6.0\LDPickupDoctor.dll'
$modsDir = Join-Path $GameDir 'Mods'

if (-not (Test-Path $dotnet)) {
    throw "No .NET SDK at $dotnet. Install one with:  irm https://dot.net/v1/dotnet-install.ps1 | iex"
}

# The interop assemblies are generated by MelonLoader on the first launch where it ACTUALLY loads,
# which on this machine took a proxy rename. Check before compiling so the error names the cause
# rather than arriving as 400 unresolved types.
$interop = Join-Path $GameDir 'MelonLoader\Il2CppAssemblies'
if (-not (Test-Path $interop)) {
    Write-Host "No interop assemblies yet - running the loader doctor." -ForegroundColor Yellow
    & (Join-Path $root 'tools\loader-doctor.ps1') -GameDir $GameDir
    throw "Start the game once so MelonLoader can generate $interop, then build again."
}

# The game holds the DLL open. Say so plainly rather than letting the copy fail with an access error.
if (Get-Process tld -ErrorAction SilentlyContinue) {
    if ($NoDeploy) {
        Write-Host "The game is running - building only." -ForegroundColor Yellow
    } else {
        throw "The Long Dark is running. Close it first, or pass -NoDeploy."
    }
}

Write-Host "building..." -ForegroundColor Cyan
& $dotnet build $project -c Release -v minimal
if ($LASTEXITCODE -ne 0) { throw "build failed" }
if (-not (Test-Path $output)) { throw "build reported success but $output is not there" }

$size = (Get-Item $output).Length
Write-Host ("built LDPickupDoctor.dll  {0:N0} bytes" -f $size) -ForegroundColor Green

if ($NoDeploy) { return }

if (-not (Test-Path $modsDir)) { New-Item -ItemType Directory -Force $modsDir | Out-Null }
Copy-Item $output (Join-Path $modsDir 'LDPickupDoctor.dll') -Force
Write-Host "deployed to $modsDir" -ForegroundColor Green

# Loader check AFTER deploying, because the useful question is not "is the file there" but "will
# anything load it".
& (Join-Path $root 'tools\loader-doctor.ps1') -GameDir $GameDir

if ($Run) {
    Start-Process -FilePath (Join-Path $GameDir 'tld.exe') -WorkingDirectory $GameDir
    Write-Host "game started - watch $GameDir\MelonLoader\Latest.log" -ForegroundColor Cyan
}
